repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.289'
    hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
      exclude: ^.*\.md$|^.*\.gitignore$
    - id: end-of-file-fixer
      exclude: ^.*\.md$|^.*\.gitignore$
    - id: check-yaml
    - id: debug-statements
  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.0
    hooks:
      - id: poetry-check
        args: ["--lock"]
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [--line-length=88]
